server {
    listen 80;
    listen [::]:80;

    server_name 43-205-103-222.nip.io _;

    root /var/www/sewa_sahayak/dist;
    index index.html;

    # Frontend Routing (React/Vite)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Backend API Routing (FastAPI)
    location /api/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Auth Routing (Google/Cognito OAuth)
    location /login {
        proxy_pass http://127.0.0.1:8000/login;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /authorize {
        proxy_pass http://127.0.0.1:8000/authorize;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Map the temp folder for static clips and redacted images
    location /temp/ {
        alias /var/www/sewa_sahayak/backend/temp/;
    }
}
